/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hipad_carrecorder_ImageProc */

#ifndef _Included_com_hipad_carrecorder_ImageProc
#define _Included_com_hipad_carrecorder_ImageProc

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_hipad_carrecorder_ImageProc
 * Method:    connectCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hipad_carrecorder_ImageProc_connectCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_hipad_carrecorder_ImageProc
 * Method:    releaseCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hipad_carrecorder_ImageProc_releaseCamera
  (JNIEnv *, jclass);

/*
 * Class:     com_hipad_carrecorder_ImageProc
 * Method:    getPreviewFrame
 * Signature: (obj)V
 */
JNIEXPORT void JNICALL Java_com_hipad_carrecorder_ImageProc_getPreviewFrame
  (JNIEnv *, jclass, jobject bitmap);

/*
 * Class:     com_hipad_carrecorder_ImageProc
 * Method:    startRecord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hipad_carrecorder_ImageProc_startRecord
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hipad_carrecorder_ImageProc
 * Method:    stopRecord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hipad_carrecorder_ImageProc_stopRecord
  (JNIEnv *, jclass);

char* jstringToChar(JNIEnv* env, jstring jstr);

#ifdef __cplusplus
}
#endif

#endif
